### ISSUE TITLE
More descriptive axis labels for the MA plot

### ISSUE THREAD

**Issue by fabianegli** [wolski/prolfqua#23]
The MA plot axis labels are quite cryptic for unexperienced users.

**Comment by wolski** [comment]
Agreed that it could be improved. Could you help me choose a better Axis labels for X and Y

"M" and "A"
"log fold change" and "mean expression"
"log fold change" and "normalized mean expression"
But what if a different normalization e.g. "asinh", is used?
or for consistency
"c1- c2" and "(c1+c2)/2"

"normalized fold change" and "normalized mean expression"

or maybe, if I would use the names of the contrasts i could generate something like
"Treatment - Control" vs "Treatment + Control"
but this would be harder to implement.

**Comment by fabianegli** [comment]
Hard to say what's best, since the data is not always the same.

I see three possible solutions:

* supply the labels when calling the ma_plot function
* have the data supplied to the ma_plot function bring along the labels
* hardcoding the labels

Since the data might be changing, it might be a good idea to use something generic as default, like "change" and "average", but I see that a valid approach would also be to use the "original" axis labels: ["logged intensity ratio (M)" and "mean logged intensities (A)"](https://www.sciencedirect.com/science/article/pii/B978012374419700007X) (have no clue "how" original that actually is, if at all).

... or another example from [Experimental Design  and  Analysis  of  Microarray  Data  Claire H. Wilson](https://www.sciencedirect.com/science/article/pii/S1874533406800043): "M = log2 (Fold Change)" and "A = log2 (Average Intensity)"

**Comment by wolski** [comment]
Hello @fabianegli ,

I decided to go with your suggestion  "logged intensity ratio (M)" and "mean logged intensities (A)".
See commit: https://github.com/wolski/prolfqua/commit/87b00f642490f451e13e8a4828bf9f96697d2681

Thanks for your help.

**Comment by fabianegli** [comment]
Great, glad to hear and that it was of help.
