### ISSUE TITLE
Simple Impute - if mean below 10% - diff to be estimated at 0

### ISSUE THREAD

**Issue by jjGG** [wolski/prolfqua#29]
Hei Witold, 

As discussed today it would be a meaningful extenstion to the simple Impute function if the log2FC would be estimated at 0 if the mean is smaller than probs (default at 0.1).

Now the log2FC is estimated in the wrong direction!

gruess - jonas
[p26828_BlandAltmann_feedOneVSfeedTwo_withImputation.pdf](https://github.com/wolski/prolfqua/files/8324826/p26828_BlandAltmann_feedOneVSfeedTwo_withImputation.pdf)

**Comment by wolski** [comment]
@jjGG created release 0.3.6 which addressed this problem.

**Comment by jjGG** [comment]
cool witold! danke
j
