### ISSUE TITLE
covr - Test Coverage for prolfqua

### ISSUE THREAD

**Issue by cpanse** [wolski/prolfqua#34]
**Is your feature request related to a problem? Please describe.**
investigate on how to apply covr to prolfqua examples

**Describe the solution you'd like**
https://cran.r-project.org/package=covr

**Comment by wolski** [comment]
Would be great if we could compute the test coverage including the examples.

It should be possible to run test coverage including the examples but did not get it working in 2019.
See the issue in the covr package
https://github.com/r-lib/covr/issues/358

**Comment by wolski** [comment]
Working
