### ISSUE TITLE
Unify naming conventions

### ISSUE THREAD

**Issue by cpanse** [wolski/prolfqua#36]
avoid switching between Camel, Pascal, snake case and mixtures thereof.

**Comment by wolski** [comment]
Done.

**Comment by wolski** [comment]
fixed with commits:

f1d4bbf39040d3be1bafb19c5bc04bdeb22f68de
254e9d0400c6862fb491010d08a99e0912f13e1f
fe2c479de88214d85432048d805ab60472304715

**Comment by wolski** [comment]
and some other commits
