### ISSUE TITLE
Broken links to Article source files

### ISSUE THREAD

**Issue by fabianegli** [wolski/prolfqua#48]
The article pages under https://fgcz.github.io/prolfqua/articles/ contain a link to their source below the title and these links seem to be broken.

e.g. on https://fgcz.github.io/prolfqua/articles/CreatingConfigurations.html the link [Source: [`../vignettes/CreatingConfigurations.Rmd`](https://github.com/wolski/prolfqua/blob/vignettes/CreatingConfigurations.Rmd) points to [https://github.com/wolski/prolfqua/blob/vignettes/CreatingConfigurations.Rmd](https://github.com/wolski/prolfqua/blob/vignettes/CreatingConfigurations.Rmd) which gives a 404 error.

**Comment by wolski** [comment]
@fabianegli Fixed.
