### ISSUE TITLE
Error with  setup_analysis()

### ISSUE THREAD

**Issue by amechakra** [wolski/prolfqua#54]
Hi,

I would like to try the vignette. The first steps go well until this one:
adata <- setup_analysis(startdata, config)

I get the following error:
"creating sampleName
Error in if (!after) c(values, x) else if (after >= lengx) c(x, values) else c(x[1L:after],  : 
  missing value where TRUE/FALSE needed"

It seems that my data contains missing values but I don't know how to handle them.
I tried : 
data <- read.table("path_to/proteinGroups.txt", sep="\t",na.strings = c(""), header=T)
data <- data %>% drop_na(c("Protein.IDs", "Gene.names", "Intensity"))
startdata <- prolfqua::tidyMQ_ProteinGroups(data)
...steps up to:
adata <- setup_analysis(startdata, config)

but I still get the same error.

Here is the link to my protein groups file: https://www.swisstransfer.com/d/34536145-ba5e-4994-8364-fa2a5aca223a

**Comment by wolski** [comment]
Dear amechakra,

The missing values are not the problem. 
Could you tell me how you specified the configuration (config) variable?
Could you also share this code? I want to reproduce the error, which would help me to give you an answer and improve the error message.


Witek

**Comment by amechakra** [comment]
Dear Witek,

Thanks for your prompt answer.


Sorry, I did not specify that I am applying the vignette : "Comparing Two Groups with prolfqua" https://fgcz.github.io/prolfqua/articles/Comparing2Groups.html


Here is the code that gave the error:

```
inputMQfile <-  file.path("/path_to/proteinGroups.txt")
inputAnnotation <- file.path("path_to/annotation.xlsx")
startdata <- prolfqua::tidyMQ_ProteinGroups(data)
annotation <- readxl::read_xlsx(inputAnnotation)
head(annotation)
startdata <- dplyr::inner_join(annotation, startdata, by = "raw.file")
startdata <- dplyr::filter(startdata, nr.peptides > 1)
atable <- AnalysisTableAnnotation$new()
atable$fileName = "raw.file"
atable$hierarchy[["protein_Id"]] <- c("proteinID")
atable$set_response("mq.protein.intensity")
config <- AnalysisConfiguration$new(atable)
adata <- setup_analysis(startdata, config) #the error comes here
```

proteinGroups: https://www.swisstransfer.com/d/34536145-ba5e-4994-8364-fa2a5aca223a
annotation: https://www.swisstransfer.com/d/75d16e41-28de-4b37-b943-cc422144cc1b




________________________________

**Comment by wolski** [comment]
Hi, Thanks for sharing the code and data. 

There are two things you need to fix. First, the raw file names in the annotation do not match those coming from tidyMQ_ProteinGroups.

```
> annotation$raw.file[1]
[1] "20210920_002_S312150_2021-08-17_HuBiceps_LCM_141_Pat1216_Diseased.raw"
> unique(startdata$raw.file)[1]
[1] "02_s312150_2021.08.17_hubiceps_lcm_141_pat1216_diseased"
```

Then you can check that the join does not return an empty data frame.
```
startdata <- dplyr::inner_join(annotation, startdata, by = "raw.file")
```

The second possible problem is that you did not specify that Condition and sample are the columns containing the explanatory variables:

```
atable <- prolfqua::AnalysisTableAnnotation$new()
atable$fileName = "raw.file"
atable$hierarchy[["protein_Id"]] <- c("proteinID")
atable$factors[["Condition"]] <- "Condition"
atable$factors[["PatientID"]] <- "sample"
```

Afterward, using prolfqua should become much more straightforward.

I hope this helps.

**Comment by amechakra** [comment]
Thank you. It perfectly works now.

________________________________
