### ISSUE TITLE
Citation points to bioRxiv

### ISSUE THREAD

**Issue by micwij** [wolski/prolfqua#61]
I just wanted to let you know that using citation("prolfqua") in R still points to the bioRxiv article and not the published article in J. Proteome Res. 2023, 22, 4, 1092–1104. The bioRxiv article also seems to still lack the information that the article is now published in J. Proteome Res. 2023, 22, 4, 1092–1104.

**Comment by wolski** [comment]
Thank you. Addressed in the new release.
