### ISSUE TITLE
volcano plot with fixed ylim (scales) cannot be "freed up" with scales="free"

### ISSUE THREAD

**Issue by jjGG** [wolski/prolfqua#67]
Hoi Witold, 

As you may have seen in the comments, one user SH realized that the volcanos are by default fixed on ylim. 
Relaxing this with the scales parameter does not work .

-> in all these volcanos, the y-axis always has the same fixed length. 
pl$volcano(scales = c("fixed"))
pl$volcano_plotly(scales = "free")
pl$volcano(scales = "free")
pl$volcano(scales = "free_y")

Gruess & bis am Dienstag
j

**Comment by wolski** [comment]
@jjGG 

I did run the examples in the prolfqua package ContrastsPlotter documentation:

cp$volcano(scales = "fixed")

![image](https://github.com/fgcz/prolfqua/assets/1926513/72097630-fa13-45ef-bd7f-c98467198dc4)

cp$volcano(scales = "free")

![image](https://github.com/fgcz/prolfqua/assets/1926513/d13d5b5a-beb3-4afa-acbd-238c6a36cd8d)


Please try to reproduce an possible error using any of the example datasets provided with prolfqua.

**Comment by wolski** [comment]
@jjGG 

I did limit the p.values to a minimum of 0.0001 ...
Now, there is a parameter `minscore`in the `volcano` function, which you can set to whatever you want.

**Comment by jjGG** [comment]
@wolski  - super cool. Thanks for tghe fix!

**Comment by jjGG** [comment]
Hei Witold, 

Leider funktioniert bei mir (prolfqua 1.1.5) der minscore parameter nicht. Eine Idee?

```
v3 <- plotter$volcano(minscore=c(1E-10))
Error in plotter$volcano(minscore = c(1e-10)) : 
  unused argument (minscore = c(1e-10))

```

**Comment by jjGG** [comment]
Super - Danke Witold.

Hat funktioniert. RTFM! 
minscore =/ min_score

```
plotter <- contr$get_Plotter()
v2 <- plotter$volcano()
gridExtra::grid.arrange(v1$FDR,v2$FDR, ncol = 1)

# relax ylim
v3 <- plotter$volcano(min_score=1E-10)

gridExtra::grid.arrange(v2$FDR,v3$FDR, ncol = 1)


```

![image](https://github.com/fgcz/prolfqua/assets/4902603/fbc3b0ae-5901-4c4f-a97f-c9eccc2ba626)
