### ISSUE TITLE
tidyMQ_ProteinGroups fiunction is not working

### ISSUE THREAD

**Issue by animesh** [wolski/prolfqua#77]
I am trying to import MaxQuant output proteinGroups.txt using https://fgcz.github.io/prolfqua/articles/Comparing2Groups.html but facing `Error: 'tidyMQ_ProteinGroups' is not an exported object from 'namespace:prolfqua' ?
`

**Comment by jjGG** [comment]
Hello Animesh, 
This function is meanwhile "out-sourced" to prolfquapp. This package builds on top of prolfqua for nice reports. 
Check-it out. If loaded, the function will work as described. 
```{r}
remotes::install_github('wolski/prolfquapp', dependencies = TRUE, force = FALSE)
```
cheers - jonas

**Comment by wolski** [comment]
Hello Animish, 
Yes, we are moving the Maxquant, DIA-NN, Spectronaut, etc, specific code to prolfquapp. 
https://github.com/prolfqua/prolfquapp

best regards

**Comment by animesh** [comment]
Thats great guys, will check it out 🤞 thanks 👍🏽
