### ISSUE TITLE
Lactylation modifications in MaxQuant

### ISSUE THREAD

**Issue by hu-jie-max** [wolski/prolfqua#90]
I have raw mass spectrometry data concerning lactylation modifications. I would like to analyze the sequence information and modification sites using MaxQuant. However, I could not find an option for lactylation modifications in the modification settings. Could you please provide specific steps on how to resolve this issue? Thank you very much!

**Comment by wolski** [comment]
@hu-jie-max Is your question possibly more related to MaxQuant?

**Comment by hu-jie-max** [comment]
thanks,yes! there is a question regarding the use of MaxQuant software for analysis. I have mass spectrometry data of proteins with lactylation modifications. Can this data be directly imported into MaxQuant for analysis? How should I specify the modification type? It appears that lactylation is not listed as an option in this software. Would I need to manually add it, and if so, how should I proceed? Thank you very much for your assistance!

**Comment by jjGG** [comment]
Hello @hu-jie-max , 

This issue page here is related to questions for using prolfqua analysis (downstream of any potential primary analysis tool such as MaxQuant).
Your question refers to the use of MaxQuant and how to configure lactlyation as a PTM. 
There are a lot of tutorials and MaxQuant summerschool videos online. I would forward you to these.

e.g: https://pharmazie.uni-greifswald.de/storages/uni-greifswald/fakultaet/mnf/pharma/biotechno/dokumente/MaxQuant_Infos_and_Tutorial_07.pdf

or: https://www.youtube.com/watch?v=d5iu6ywgw5U

best regards
jonas

**Comment by hu-jie-max** [comment]
Thank you very much for your assistance, and I apologize for the delayed response. I will try your suggestions to address my issue. Thank you!
